openapi: 3.0.0
info:
  title: Referrals VAPI
  version: 1.0.0
  description: Prefix all endpoints with /referrals
paths:
  /listReferrals:
    post:
      summary: List referrals
      tags:
        - Referrals
      responses:
        '200':
          description: Task list
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Referral'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /acceptReferral:
    post:
      summary: Accept referral request
      tags:
        - Referrals
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                referrerUserId:
                  type: string
                referredUsername:
                  type: string
      responses:
        '200':
          description: accepted referral
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Referral'
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
components:
  schemas:
    Referral:
      type: object
      properties:
        id:
          type: string
        referredUserId:
          type: string
        referredUserName:
          type: string
        referredJoinedAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        